/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ScriptId = IDL.Text;
export const ProjectId = IDL.Text;
export const Stage = IDL.Variant({
  'filming' : IDL.Null,
  'editing' : IDL.Null,
  'published' : IDL.Null,
  'exporting' : IDL.Null,
  'planning' : IDL.Null,
});
export const ReportId = IDL.Text;
export const Status = IDL.Variant({ 'resolved' : IDL.Null, 'open' : IDL.Null });
export const Time = IDL.Int;
export const Category = IDL.Variant({
  'audio' : IDL.Null,
  'other' : IDL.Null,
  'video' : IDL.Null,
  'lighting' : IDL.Null,
  'export' : IDL.Null,
});
export const ProblemReport = IDL.Record({
  'id' : ReportId,
  'status' : Status,
  'resolutionNote' : IDL.Opt(IDL.Text),
  'createdAt' : Time,
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'category' : Category,
});
export const PromptId = IDL.Text;
export const Tag = IDL.Text;
export const PromptType = IDL.Variant({
  'voice' : IDL.Null,
  'image' : IDL.Null,
});
export const SavedPrompt = IDL.Record({
  'id' : PromptId,
  'title' : IDL.Text,
  'createdAt' : Time,
  'tags' : IDL.Vec(Tag),
  'user' : IDL.Principal,
  'promptText' : IDL.Text,
  'promptType' : PromptType,
});
export const Script = IDL.Record({
  'id' : ScriptId,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'hook' : IDL.Text,
  'createdAt' : Time,
  'tags' : IDL.Vec(Tag),
  'user' : IDL.Principal,
  'callToAction' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const VideoProject = IDL.Record({
  'id' : ProjectId,
  'title' : IDL.Text,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'updatedAt' : IDL.Opt(Time),
  'stage' : Stage,
  'notes' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createScript' : IDL.Func(
      [ScriptId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'createVideoProject' : IDL.Func(
      [ProjectId, IDL.Text, Stage, IDL.Text],
      [],
      [],
    ),
  'deleteScript' : IDL.Func([ScriptId], [], []),
  'getAllProblemReports' : IDL.Func([], [IDL.Vec(ProblemReport)], ['query']),
  'getAllSavedPrompts' : IDL.Func([], [IDL.Vec(SavedPrompt)], ['query']),
  'getAllScripts' : IDL.Func([], [IDL.Vec(Script)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProblemReportById' : IDL.Func([ReportId], [ProblemReport], ['query']),
  'getPromptById' : IDL.Func([PromptId], [SavedPrompt], ['query']),
  'getScriptById' : IDL.Func([ScriptId], [Script], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserVideoProjects' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(VideoProject)],
      ['query'],
    ),
  'getVideoProjectById' : IDL.Func([ProjectId], [VideoProject], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resolveProblemReport' : IDL.Func([ReportId, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePrompt' : IDL.Func(
      [PromptId, PromptType, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'submitProblemReport' : IDL.Func([ReportId, Category, IDL.Text], [], []),
  'updateScript' : IDL.Func(
      [ScriptId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'updateVideoProject' : IDL.Func(
      [ProjectId, IDL.Text, Stage, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ScriptId = IDL.Text;
  const ProjectId = IDL.Text;
  const Stage = IDL.Variant({
    'filming' : IDL.Null,
    'editing' : IDL.Null,
    'published' : IDL.Null,
    'exporting' : IDL.Null,
    'planning' : IDL.Null,
  });
  const ReportId = IDL.Text;
  const Status = IDL.Variant({ 'resolved' : IDL.Null, 'open' : IDL.Null });
  const Time = IDL.Int;
  const Category = IDL.Variant({
    'audio' : IDL.Null,
    'other' : IDL.Null,
    'video' : IDL.Null,
    'lighting' : IDL.Null,
    'export' : IDL.Null,
  });
  const ProblemReport = IDL.Record({
    'id' : ReportId,
    'status' : Status,
    'resolutionNote' : IDL.Opt(IDL.Text),
    'createdAt' : Time,
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'category' : Category,
  });
  const PromptId = IDL.Text;
  const Tag = IDL.Text;
  const PromptType = IDL.Variant({ 'voice' : IDL.Null, 'image' : IDL.Null });
  const SavedPrompt = IDL.Record({
    'id' : PromptId,
    'title' : IDL.Text,
    'createdAt' : Time,
    'tags' : IDL.Vec(Tag),
    'user' : IDL.Principal,
    'promptText' : IDL.Text,
    'promptType' : PromptType,
  });
  const Script = IDL.Record({
    'id' : ScriptId,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'hook' : IDL.Text,
    'createdAt' : Time,
    'tags' : IDL.Vec(Tag),
    'user' : IDL.Principal,
    'callToAction' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const VideoProject = IDL.Record({
    'id' : ProjectId,
    'title' : IDL.Text,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'updatedAt' : IDL.Opt(Time),
    'stage' : Stage,
    'notes' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createScript' : IDL.Func(
        [ScriptId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'createVideoProject' : IDL.Func(
        [ProjectId, IDL.Text, Stage, IDL.Text],
        [],
        [],
      ),
    'deleteScript' : IDL.Func([ScriptId], [], []),
    'getAllProblemReports' : IDL.Func([], [IDL.Vec(ProblemReport)], ['query']),
    'getAllSavedPrompts' : IDL.Func([], [IDL.Vec(SavedPrompt)], ['query']),
    'getAllScripts' : IDL.Func([], [IDL.Vec(Script)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProblemReportById' : IDL.Func([ReportId], [ProblemReport], ['query']),
    'getPromptById' : IDL.Func([PromptId], [SavedPrompt], ['query']),
    'getScriptById' : IDL.Func([ScriptId], [Script], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserVideoProjects' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(VideoProject)],
        ['query'],
      ),
    'getVideoProjectById' : IDL.Func([ProjectId], [VideoProject], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resolveProblemReport' : IDL.Func([ReportId, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePrompt' : IDL.Func(
        [PromptId, PromptType, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'submitProblemReport' : IDL.Func([ReportId, Category, IDL.Text], [], []),
    'updateScript' : IDL.Func(
        [ScriptId, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'updateVideoProject' : IDL.Func(
        [ProjectId, IDL.Text, Stage, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };