/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'audio' : null } |
  { 'other' : null } |
  { 'video' : null } |
  { 'lighting' : null } |
  { 'export' : null };
export interface ProblemReport {
  'id' : ReportId,
  'status' : Status,
  'resolutionNote' : [] | [string],
  'createdAt' : Time,
  'user' : Principal,
  'description' : string,
  'category' : Category,
}
export type ProjectId = string;
export type PromptId = string;
export type PromptType = { 'voice' : null } |
  { 'image' : null };
export type ReportId = string;
export interface SavedPrompt {
  'id' : PromptId,
  'title' : string,
  'createdAt' : Time,
  'tags' : Array<Tag>,
  'user' : Principal,
  'promptText' : string,
  'promptType' : PromptType,
}
export interface Script {
  'id' : ScriptId,
  'title' : string,
  'body' : string,
  'hook' : string,
  'createdAt' : Time,
  'tags' : Array<Tag>,
  'user' : Principal,
  'callToAction' : string,
}
export type ScriptId = string;
export type Stage = { 'filming' : null } |
  { 'editing' : null } |
  { 'published' : null } |
  { 'exporting' : null } |
  { 'planning' : null };
export type Status = { 'resolved' : null } |
  { 'open' : null };
export type Tag = string;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoProject {
  'id' : ProjectId,
  'title' : string,
  'createdAt' : Time,
  'user' : Principal,
  'updatedAt' : [] | [Time],
  'stage' : Stage,
  'notes' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createScript' : ActorMethod<
    [ScriptId, string, string, string, string, Array<string>],
    undefined
  >,
  'createVideoProject' : ActorMethod<
    [ProjectId, string, Stage, string],
    undefined
  >,
  'deleteScript' : ActorMethod<[ScriptId], undefined>,
  'getAllProblemReports' : ActorMethod<[], Array<ProblemReport>>,
  'getAllSavedPrompts' : ActorMethod<[], Array<SavedPrompt>>,
  'getAllScripts' : ActorMethod<[], Array<Script>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProblemReportById' : ActorMethod<[ReportId], ProblemReport>,
  'getPromptById' : ActorMethod<[PromptId], SavedPrompt>,
  'getScriptById' : ActorMethod<[ScriptId], Script>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserVideoProjects' : ActorMethod<[Principal], Array<VideoProject>>,
  'getVideoProjectById' : ActorMethod<[ProjectId], VideoProject>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resolveProblemReport' : ActorMethod<[ReportId, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePrompt' : ActorMethod<
    [PromptId, PromptType, string, string, Array<string>],
    undefined
  >,
  'submitProblemReport' : ActorMethod<[ReportId, Category, string], undefined>,
  'updateScript' : ActorMethod<
    [ScriptId, string, string, string, string, Array<string>],
    undefined
  >,
  'updateVideoProject' : ActorMethod<
    [ProjectId, string, Stage, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];